# GitHub Actions Workflow: Build Windows Executable for Artocarpus Scrcpy GUI
# This workflow builds a Windows executable using PyInstaller with --onedir format
# Users will need to provide their own scrcpy and adb installations

name: Build Windows Executable (OneDir Format)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      # --- Step 1: Checkout Repository ---
      - name: Checkout Repository
        uses: actions/checkout@v4

      # --- Step 2: Set up Python ---
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # --- Step 3: Install Dependencies ---
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller ttkthemes

      # --- Step 4: Create Version Info ---
      - name: Create Version Info
        run: |
          $VERSION = "v5.3"
          $BUILD_TIME = Get-Date -Format "yyyyMMdd-HHmm"
          $ARCH = "x64"
          echo "VERSION=$VERSION" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "BUILD_TIME=$BUILD_TIME" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "ARCH=$ARCH" | Out-File -FilePath $env:GITHUB_ENV -Append

      # --- Step 5: Build with PyInstaller (OneDir Format) ---
      - name: Build with PyInstaller
        run: |
          # 创建 PyInstaller spec 文件或直接使用命令行
          pyinstaller --onefile --windowed --name "Artocarpus_scrcpy_gui" --icon=artocarpus_icon.ico scrcpy_gui.py
          # 注意：这里使用了 --onefile，如果需要 --onedir 请改为：
          # pyinstaller --onedir --windowed --name "Artocarpus_scrcpy_gui" --icon=artocarpus_icon.ico scrcpy_gui.py

      # --- Step 6: Prepare Distribution Package ---
      - name: Prepare Distribution Package
        run: |
          $VERSION = "${{ env.VERSION }}"
          $BUILD_TIME = "${{ env.BUILD_TIME }}"
          $ARCH = "${{ env.ARCH }}"
          $ZIP_NAME = "Artocarpus_scrcpy_gui-${VERSION}-${BUILD_TIME}-${ARCH}.zip"
          
          # 创建分发目录
          New-Item -ItemType Directory -Path "dist/Artocarpus_scrcpy_gui" -Force
          
          # 复制可执行文件和依赖项
          Copy-Item "dist/Artocarpus_scrcpy_gui.exe" -Destination "dist/Artocarpus_scrcpy_gui/"
          Copy-Item "artocarpus_icon.png" -Destination "dist/Artocarpus_scrcpy_gui/"
          
          # 创建 README 文件说明需要单独安装 scrcpy 和 adb
          $README_CONTENT = @"
          Artocarpus Scrcpy GUI - Windows Version $VERSION

          This is a GUI for the scrcpy Android screen mirroring tool.

          IMPORTANT: This package does NOT include scrcpy or adb.
          You need to install them separately:

          1. Download scrcpy from: https://github.com/Genymobile/scrcpy
          2. Download Android Platform Tools (adb) from: https://developer.android.com/studio/releases/platform-tools

          After installation, you can specify the paths to scrcpy and adb in the GUI's configuration.

          Build Date: $BUILD_TIME
          "@
          $README_CONTENT | Out-File -FilePath "dist/Artocarpus_scrcpy_gui/README.txt" -Encoding UTF8
          
          # 压缩为 ZIP 文件
          Compress-Archive -Path "dist/Artocarpus_scrcpy_gui/*" -DestinationPath $ZIP_NAME -Force
          
          echo "ZIP_NAME=$ZIP_NAME" | Out-File -FilePath $env:GITHUB_ENV -Append

      # --- Step 7: Upload to GitHub Release ---
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Artocarpus_scrcpy_gui ${{ env.VERSION }} Windows (Build ${{ env.BUILD_TIME }})
          tag_name: windows-${{ env.VERSION }}-${{ env.BUILD_TIME }}
          files: ${{ env.ZIP_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
